Update db.yml

diff --git a/.github/workflows/db.yml b/.github/workflows/db.yml
--- a/.github/workflows/db.yml
+++ b/.github/workflows/db.yml
@@ -52,7 +52,14 @@ jobs:
           fi
           echo "RELEASE_FOLDER=$RELEASE_FOLDER" >> $GITHUB_ENV
           echo "✅ Extracted release folder: $RELEASE_FOLDER."
-
+ 
+      - name: Validate Release Folder in Releasemanagement Branch
+        run: |
+          if [ ! -d "$BASE_PATH/$RELEASE_FOLDER" ]; then
+            echo "❌ Error: Release folder $RELEASE_FOLDER not found in $BASE_PATH!"
+            exit 1
+          fi
+          echo "✅ Release folder $RELEASE_FOLDER found."
  
       - name: Checkout DB Scripts (db-scripts branch)
         uses: actions/checkout@v4
@@ -62,15 +69,6 @@ jobs:
           ref: ${{ env.SCRIPT_BRANCH }}
           path: 'NAAP_DB'
  
-      - name: Validate Release Folder in DB Scripts Branch
-        run: |
-          DB_SCRIPTS_PATH="NAAP_DB/$RELEASE_FOLDER"
-          if [ ! -d "$DB_SCRIPTS_PATH" ]; then
-            echo "❌ Error: Release folder $RELEASE_FOLDER not found in db-scripts branch!"
-            exit 1
-          fi
-          echo "✅ Release folder $RELEASE_FOLDER found in db-scripts branch."
- 
       - name: Set up Java
         uses: actions/setup-java@v3
         with:
@@ -79,11 +77,20 @@ jobs:
  
       - name: Install Liquibase
         run: |
+          echo "✅ Downloading Liquibase..."
           curl -LO https://github.com/liquibase/liquibase/releases/download/v4.23.2/liquibase-4.23.2.tar.gz
+
+          echo "📦 Extracting Liquibase..."
           tar -xvzf liquibase-4.23.2.tar.gz
-          chmod +x liquibase
-          sudo mv liquibase /usr/local/bin/
-          echo "✅ Liquibase installed."
+
+          echo "🚀 Moving Liquibase to /usr/local/bin"
+          sudo mkdir -p /usr/local/bin/liquibase
+          sudo mv liquibase /usr/local/bin/liquibase/liquibase
+          sudo mv internal /usr/local/bin/liquibase/internal
+          sudo ln -sf /usr/local/bin/liquibase/liquibase /usr/local/bin/liquibase
+
+          echo "✅ Liquibase installed successfully!"
+
  
       - name: Execute Liquibase Scripts for Multiple Schemas
         env:
